FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
COPY . .
WORKDIR /Gdal.Web
RUN dotnet publish -c Release -o /app
ENV PROJ_LIB=/app/runtimes/linux-x64/native/maxrev.gdal.core.libshared/
WORKDIR /app
ENTRYPOINT ["dotnet", "Gdal.Web.dll"]